### ISSUE TITLE
Path doesn't expand parameter

### ISSUE THREAD

**Issue by camlafit** [discourse/pups#32]
Hello

I've tried to set a file with parameter value without success. 
For exemple with  : 
```
params:
  home: /var/www/discourse
  - file:
     path: $home/bin/script
     chmod: +x
     contents: |
       #!/bin/bash
       echo "I'm a script"
```

pups doesn't expand $home and can't create _/var/www/discourse/script_

My purpose was to mode all paths set in template to parameter and prevent them as hardcoded .

Any idea to workaround about this.
